name: Deploy to Google Cloud Run

on:
  push:
    branches:
      - main # Change this to your deployment branch if necessary

jobs:
  deploy:
    name: Deploy to Cloud Run
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Authenticate with Google Cloud
      uses: google-github-actions/auth@v1
      with:
        credentials_json: ${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}

    - name: Configure Google Cloud SDK
      run: gcloud config set project ${{ secrets.GCP_PROJECT_ID }}

    - name: Build Docker Image
      run: |
        docker build -f InSyncAPI/InSyncAPI/Dockerfile -t gcr.io/your-project-id/insync-api InSyncAPI/InSyncAPI .

    - name: Push Docker Image to Container Registry
      run: |
        docker push gcr.io/${{ secrets.GCP_PROJECT_ID }}/insync-api

    - name: Deploy to Cloud Run
      run: |
        gcloud run deploy insync-api \
          --image gcr.io/${{ secrets.GCP_PROJECT_ID }}/insync-api \
          --platform managed \
          --region ${{ secrets.GCP_REGION }} \
          --allow-unauthenticated \
          --memory 512Mi
