name: Docker CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:  
  build:

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up docker for CI
      run: docker build -f InSyncAPI/Dockerfile --tag thesis/insyncapi:$(date +%s) .
