name: Docker CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:  
  build:

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up docker for CI
      run: docker build -f InSyncAPI/InSyncAPI/Dockerfile --tag quangminhh/insyncapi:latest .
    - name: Login docker for CI
      run:
        docker login -u quangminhh -p ${{secrets.DOCKER_HUB_TOKEN}}
    - name: Push docker for CI
      run:
        docker push quangminhh/insyncapi:latest
